baseURL = "https://chrissalch.com/"
languageCode = "en-us"
title = "Chris Salch"
theme = "hermit"

googleAnalytics = "UA-28271605-1"
[params]
  homeSubtitle = "The identity function."
  customCSS = [ "css/blog.css" ]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/arlaneenalra"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/arlaneenalra/"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/arlaneenalra"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/chris-salch-94a6784/"

[menu]
  [[menu.main]]
    name = "Books (fiction)"
    url = "https://www.facebook.com/author.christophersalch/"
  [[menu.main]]
    name = "Art"
    url = "https://www.facebook.com/artist.christophersalch/"
  [[menu.main]]
    name = "Old Blog"
    url = "old-blog/"


